Create mute.js
Roblox-Developers-CodeSkids/RobloxDevelopersV2 pull request #3
Opened 2020-10-09 01:42 UTC by shah1012

2020-10-09 01:44 UTC, SovietKitsune commented on commands/mute.js
> +    let mmber = args.member;
Change to member

2020-10-09 01:45 UTC, SovietKitsune commented on commands/mute.js
> +    let MuteRole = msg.guild.roles.cache.get("484337500333277214");  //replace with server role id
Get id from the toml config
```js
const { parse } = require('toml');
const { readFileSync } = require('fs');

let { muted }= parse(readFileSync('config.toml'))
```

2020-10-09 01:46 UTC, SovietKitsune commented on commands/mute.js
> +    let MuteRole = msg.guild.roles.cache.get("484337500333277214");  //replace with server role id
Prettier was not ran as it would replace double quotes to single quotes

2020-10-09 01:47 UTC, SovietKitsune commented on commands/mute.js
> +        },
Should default to false to signify that the mute is not going to be automatically removed

2020-10-09 01:53 UTC, shah1012 commented on commands/mute.js
> +    let MuteRole = msg.guild.roles.cache.get("484337500333277214");  //replace with server role id
for muted would i still do 

```member.role.add(muted.id)```

2020-10-09 01:54 UTC, SovietKitsune commented on commands/mute.js
> +    let MuteRole = msg.guild.roles.cache.get("484337500333277214");  //replace with server role id
You would do
```js
member.role.add(muted)
```

2020-10-10 01:35 UTC, SovietKitsune requested changes

2020-10-10 01:35 UTC, SovietKitsune commented on commands/mute.js
>      }, ms(time));
You should check if time is false, if it is, don't specify a time in the reply and don't set a timeout.

2020-10-10 01:35 UTC, SovietKitsune commented on commands/mute.js
> +    if (!args.time) return msg.reply('Please Specify a time!');
This should be removed as if there is no time specified, the mute is unlimited.

2020-10-10 01:35 UTC, SovietKitsune commented on commands/mute.js
> +    if (!muted) return msg.reply('Cant find the Mute Role!');
Should be `can not` or `couldn't`

2020-10-12 22:30 UTC, closed without merging